#pragma once

#include <string>

enum class MessageEnumerator
{
    None,
    ResidentialNeeded,
    CommercialNeeded,
    IndustrialNeeded,
    RoadsNeeded,
    RailNeeded,
    PowerNeeded,
    StadiumNeeded,
    SeaportNeeded,
    AirportNeeded,
    PollutionHigh,
    CrimeHigh,
    TrafficJamsReported,
    FireDepartmentNeeded,
    PoliceDepartmentNeeded,
    BlackoutsReported,
    TaxesHigh,
    RoadsDeteriorating,
    FireDefunded,
    PoliceDefunded,
    FireReported,
    MonsterReported,
    TornadoReported,
    EarthquakeReported,
    PlaneCrashed,
    ShipWrecked,
    TrainCrashed,
    HelicopterCrashed,
    UnemploymentHigh,
    CoffersEmpty,
    FirebombingReported,
    ParksNeeded,
    ExplosionReported,
    InsufficientFunds,
    MustBulldoze,
    ReachedTown,
    ReachedCity,
    ReachedCapital,
    ReachedMetropolis,
    ReachedMegalopolis,
    BrownoutsReported,
    HeavyTrafficReported,
    FloodingReported,
    NuclearMeltdownReported,
    RiotsReported,
    EndOfDemo,
    NoSoundServer,
    NoMultiplayerLicense,
    NewCityStarted,
    CityRestored
};

const std::string& GetIndString(int /*id*/, MessageEnumerator);
